# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: html to pdf
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://lkiitkgp.github.io/me/
        outputFile: ./resume.pdf
        usePuppeteer: true
        useScreen: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./resume.pdf
